rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
# whitelist
branches:
  only:
    - master
# Needed for selenium browser
before_script: sh ./retry_selenium_browser_start.sh


notifications:
  email:
    - chaffeqa@gmail.com